---
kind: pipeline
type: docker
name: default
steps:
  - name: check
    image: node:latest
    commands:
      - npm ci
      - npm run lint
  - name: build
    image: node:latest
    commands:
      - dpkg --add-architecture i386
      - apt update -y
      - apt-get upgrade -y
      - apt install mono-devel wine32 wine64 -y
      - npm ci
      - npm run build
    when:
      event:
        - tag
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files: out/make/squirrel.windows/x64/*
    when:
      event:
        - tag
