---
kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: stefanscherer/node-windows:latest
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - npm ci
      - npm run publish --dry-run
  - name: release
    image: node:latest
    platform:
      os: windows
      arch: amd64
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - npm ci
      - npm run publish
    when:
      event:
        - tag
